version: "3"

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web-secured.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      # - "443:443"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    network_mode: bridge

  reverse-proxy-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
